### PR TITLE
ftr: change header for eclipse movement

### PR DESCRIPTION
**Pull request by gregors101**
[TRACEFOSS-763]

### CODE REVIEW

**Comment by ds-ext-dskrzypczak** [comment]
@gregors101 FYI I've just merged notification branch to main, so probably you will need to update some files with new version of header :)

**Comment by gregors101** [comment]
@ds-ext-dskrzypczak I merged now the notification branch

**Comment by gregors101** [comment]
@evia-fbedarf IntelliJ adds a newline at the end of the header file, therefore there is an additional newline at each header? Is this ok, or is this an issue. Maybe you check the branch with your local apple environment ...

**Review by evia-fbedarf — APPROVED** [review]
LGMT

**Review by mkanal — APPROVED** [review]

**Pull request merged**
